site_name: Gitea Auto Mirror Documentation
markdown_extensions:
  - admonition
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - toc.integrate
    - content.action.edit
    - content.action.view
nav:
  - Home: index.md
  - Installing:
    - Introduction: installing/index.md
    - Docker Compose: installing/docker-compose.md
    - Kubernetes: installing/kubernetes.md
  - Configuration: 
    - Introduction: configuring/index.md
    - Source Configuration: 
      - Configuration Options: configuring/source.md
    - Gitea Auto Mirror Configuration:  
      - Configuration Variables: configuring/gitea-auto-mirror/variables.md
      - Authentication: configuring/gitea-auto-mirror/authentication.md
    - Mirror Configuration: 
      - Configuration Options: configuring/mirror.md
repo_url: https://github.com/LightJack05/gitea-auto-mirror
edit_uri: edit/main/docs/
plugins:
  - privacy
