site_name: Gitea Auto Mirror Documentation
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
nav:
  - Home: index.md
  - Installing:
    - Introduction: installing/index.md
    - Docker Compose: installing/docker-compose.md
    - Kubernetes: installing/kubernetes.md
  - Configuration: configuring/index.md
